language: python
sudo: required
dist: xenial
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7
install:
  - pip install pipenv
  # Temporary: some python versions & pip 18.1 have issues with pipenv
  - pipenv run python -m pip install -U pip==18.0
  # Fixes issue where package versions may not exist on python version
  - pipenv update --dev
script:
  - pipenv run tox
