language: python
sudo: required
dist: xenial
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7
install:
  - pip install pipenv
  - pipenv run python -m pip install -U pip==18.0
  - pipenv install --dev
script:
  - pipenv run tox
