language: python
sudo: required
dist: xenial
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7
install:
  - pip install pipenv
  - pipenv run pip install pip --update
  - pipenv install --dev
script:
  - pipenv run tox
